### ISSUE TITLE
Coding task: read abstracts to code for relevance

### ISSUE THREAD

**Issue by JBGruber** [JBGruber/opinion-wg2#9]
After establishing ICR in #7, we will code the full set of abstracts.

**Comment by valeriehase** [comment]
First batch of N = 1,002 abstracts coded, 554 relevant abstracts defined. Tbd: Do we want to code more?

**Comment by JBGruber** [comment]
I assume we are done with this, but I don't think we should close it just yet before we know how well #19 works.

**Comment by JBGruber** [comment]
Done!
